/* Converted to D from openinput.h by htod */
module openinput.openinput;
/*
 * openinput.h : Top-level include file for OpenInput
 *
 * This file is a part of the OpenInput library.
 * Copyright (C) 2005  Jakob Kjaer <makob@makob.dk>.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

/* ******************************************************************** */

//C     #ifndef _OPENINPUT_H_
//C     #define _OPENINPUT_H_

//C     #ifdef __cplusplus
//C     extern "C" {
//C     #endif

/* ******************************************************************** */

/**
 * @ingroup PMain
 * @{
 */

// Fix Windows
//C     #if !defined(WIN32) && defined(_WIN32)
//C     #define WIN32
//C     #endif

// Export keyword
//C     #ifndef DECLSPEC
//C     #  ifdef WIN32
//C     #    define DECLSPEC __declspec(dllexport) /**< Export keyword, Windows */
//C     #  else
//C     #    define DECLSPEC  /**< Export keyword, default */
//C     #  endif
//C     #endif

// Calling convention
//C     #ifndef OICALL
//C     #    define OICALL  /**< Calling convention, default */
//C     #endif

/** @} */

/* ******************************************************************** */

/**
 * @ingroup PMain
 * @{
 */
//C     #define OI_MAJOR_VERSION 0 /**< Major version number (autogenerated) */
//C     #define OI_MINOR_VERSION 2 /**< Minor version number (autogenerated) */
const OI_MAJOR_VERSION = 0;
//C     #define OI_PATCH_VERSION 3 /**< Patch version number (autogenerated) */
const OI_MINOR_VERSION = 2;
//C     #define OI_VERSION "0.2.3" /**< Version as a string (autogenerated) */
const OI_PATCH_VERSION = 3;
/** @} */

/* ******************************************************************** */

//C     #include "openinput_types.h"
import openinput.openinput_types;
//C     #include "openinput_keyboard.h"
import openinput.openinput_keyboard;
//C     #include "openinput_mouse.h"
import openinput.openinput_mouse;
//C     #include "openinput_joystick.h"
import openinput.openinput_joystick;
//C     #include "openinput_action.h"
import openinput.openinput_action;
//C     #include "openinput_events.h"
import openinput.openinput_events;
//C     #include "openinput_api.h"
import openinput.openinput_api;

/* ******************************************************************** */

//C     #ifdef __cplusplus
//C     }
//C     #endif

//C     #endif
